# Generated by Django 4.1 on 2022-09-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='AdminUserImages/')),
                ('profile_picture_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSlote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField()),
                ('zoomlink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('availableslotes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.availableslote')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_created_date', models.DateField()),
                ('unique_link', models.URLField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.event')),
            ],
        ),
        migrations.AddField(
            model_name='availableslote',
            name='caledardates_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.calendardate'),
        ),
    ]
