# Generated by Django 4.1 on 2022-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_adminuser_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], default='m', max_length=1),
        ),
    ]
