# Generated by Django 4.1 on 2022-09-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_adminuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='email_verified',
        ),
    ]
