# Generated by Django 4.1 on 2022-09-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_adminuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_agenda',
            field=models.CharField(default='Meeting', max_length=100),
        ),
    ]
