# Generated by Django 4.1 on 2022-09-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_event_event_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableslote',
            old_name='caledardates_id',
            new_name='calendardates_id',
        ),
    ]
